dataset:
  name: cadets_e3
experiment_prefix: cadets_e3_experiment_1
storage:
  graph_root_dir: ./data/graphs
graph_management:
  force_reload: false
times:
  train_start: ["2018-04-02 00:00:00"]
  train_end: ["2018-04-05 23:59:59"]
  test_start: ["2018-04-06 00:00:00"]
  test_end: ["2018-04-13 23:59:59"]
  context_size: 120 # in minutes
  step_size: 120 # in minutes
location_transformer:
  max_location_length: 100
  hidden_dim: 16
  embedding_dim: 8 
  num_layers: 2
  nhead: 4
  num_epochs: 10
  patience: 3
  batch_size: 32
  positional_encoding_max_len: 5000
  positional_encoding_div_term_hyperparam: 10000.0
  learning_rate: 0.001
  device: cuda
detection:
  num_neighbors: [-1,-1]
  batch_size: 64
  epochs: 4
  device: cuda
  learning_rate: 0.01
  hidden_dim: 128
  heads: 4
  num_layers: 2
  dropout: 0.1
  weight_decay: 0.0001
  scheduler_factor: 0.5
  scheduler_patience: 5
  scheduler_mode: min
  shuffle_train_paths: true
  shuffle_train_batches: true