import string
from enum import Enum


class NodeType(str, Enum):
    """Canonical node types used across the project."""

    SUBJECT = "subject"
    FILE = "file"
    NETFLOW = "netflow"


class EdgeColumns(str, Enum):
    """Edge column names expected from the database layer."""

    SRC_NODE = "src_node"
    SRC_INDEX_ID = "src_index_id"
    OPERATION = "operation"
    DST_NODE = "dst_node"
    DST_INDEX_ID = "dst_index_id"
    TIMESTAMP = "timestamp_rec"


class NodeColumns(str, Enum):
    """Node column names expected from the database layer."""

    UUID = "node_uuid"
    INDEX_ID = "index_id"
    TYPE = "type"
    CMD = "cmd"
    PATH = "path"
    SRC_ADDR = "src_addr"
    SRC_PORT = "src_port"
    DST_ADDR = "dst_addr"
    DST_PORT = "dst_port"


class NodeTableName(str, Enum):
    """Database table names for graph nodes."""

    SUBJECT = "subject_node_table"
    FILE = "file_node_table"
    # SUBJECT = "subject_node_table_lotl"
    # FILE = "file_node_table_lotl"
    NETFLOW = "netflow_node_table"


class EventTable(str, Enum):
    """Database table names for events/edges."""

    EVENT = "event_table"


class OptcOperation(str, Enum):
    """Operations used for OPTC datasets."""

    OPEN = "OPEN"
    READ = "READ"
    CREATE = "CREATE"
    MESSAGE = "MESSAGE"
    MODIFY = "MODIFY"
    START = "START"
    RENAME = "RENAME"
    DELETE = "DELETE"
    TERMINATE = "TERMINATE"
    WRITE = "WRITE"


class Atlasv2Operation(str, Enum):
    """Operations used for Atlasv2 datasets."""

    FILE_CLOSED = "FILE_CLOSED"
    FILE_CREATED = "FILE_CREATED"
    FILE_DELETED = "FILE_DELETED"
    FILE_OPENED = "FILE_OPENED"
    FILE_READ = "FILE_READ"
    FILE_RESTORED = "FILE_RESTORED"
    FILE_TRUNCATED = "FILE_TRUNCATED"
    FILE_WRITTEN = "FILE_WRITTEN"
    MODULE_LOADED = "MODULE_LOADED"
    NETFLOW_CONNECTED = "NETFLOW_CONNECTED"
    NETFLOW_CREATED = "NETFLOW_CREATED"
    NETFLOW_DISCONNECTED = "NETFLOW_DISCONNECTED"
    NETFLOW_PACKET_RECEIVED = "NETFLOW_PACKET_RECEIVED"
    NETFLOW_PACKET_SENT = "NETFLOW_PACKET_SENT"
    PROCESS_EXECUTED = "PROCESS_EXECUTED"
    REGISTRY_KEY_CREATED = "REGISTRY_KEY_CREATED"
    REGISTRY_KEY_DELETED = "REGISTRY_KEY_DELETED"
    REGISTRY_KEY_LOADED = "REGISTRY_KEY_LOADED"
    REGISTRY_KEY_OPENED = "REGISTRY_KEY_OPENED"
    REGISTRY_VALUE_DELETED = "REGISTRY_VALUE_DELETED"
    REGISTRY_VALUE_WRITTEN = "REGISTRY_VALUE_WRITTEN"

    # ACTION_FILE_UNDELETE = "ACTION_FILE_UNDELETE"
    # ACTION_FILE_OPEN_SET_ATTRIBUTES = "ACTION_FILE_OPEN_SET_ATTRIBUTES"
    # ACTION_FILE_CREATE = "ACTION_FILE_CREATE"
    # ACTION_FILE_OPEN_DELETE = "ACTION_FILE_OPEN_DELETE"
    # ACTION_FILE_OPEN_SET_SECURITY = "ACTION_FILE_OPEN_SET_SECURITY"
    # ACTION_FILE_TRUNCATE = "ACTION_FILE_TRUNCATE"
    # ACTION_FILE_MOD_OPEN = "ACTION_FILE_MOD_OPEN"
    # ACTION_FILE_DELETE = "ACTION_FILE_DELETE"
    # ACTION_FILE_LAST_WRITE = "ACTION_FILE_LAST_WRITE"
    # ACTION_FILE_OPEN_WRITE = "ACTION_FILE_OPEN_WRITE"
    # ACTION_FILE_RENAME = "ACTION_FILE_RENAME"
    # ACTION_FILE_OPEN_READ = "ACTION_FILE_OPEN_READ"
    # ACTION_FILE_WRITE = "ACTION_FILE_WRITE"
    # ACTION_OPEN_KEY_DELETE = "ACTION_OPEN_KEY_DELETE"
    # ACTION_WRITE_VALUE = "ACTION_WRITE_VALUE"
    # ACTION_DELETE_VALUE = "ACTION_DELETE_VALUE"
    # ACTION_OPEN_KEY_READ = "ACTION_OPEN_KEY_READ"
    # ACTION_DELETE_KEY = "ACTION_DELETE_KEY"
    # ACTION_LOAD_KEY = "ACTION_LOAD_KEY"
    # ACTION_CREATE_KEY = "ACTION_CREATE_KEY"
    # ACTION_OPEN_KEY_WRITE = "ACTION_OPEN_KEY_WRITE"
    # ACTION_LOAD_MODULE = "ACTION_LOAD_MODULE"
    # ACTION_PROCESS_TERMINATE = "ACTION_PROCESS_TERMINATE"
    # ACTION_PROCESS_DISCOVERED = "ACTION_PROCESS_DISCOVERED"
    # ACTION_CREATE_PROCESS = "ACTION_CREATE_PROCESS"
    # ACTION_CREATE_PROCESS_EFFECTIVE = "ACTION_CREATE_PROCESS_EFFECTIVE"
    # ACTION_DUP_THREAD_HANDLE = "ACTION_DUP_THREAD_HANDLE"
    # ACTION_DUP_PROCESS_HANDLE = "ACTION_DUP_PROCESS_HANDLE"
    # ACTION_OPEN_PROCESS_HANDLE = "ACTION_OPEN_PROCESS_HANDLE"
    # ACTION_OPEN_THREAD_HANDLE = "ACTION_OPEN_THREAD_HANDLE"
    # ACTION_LOAD_SCRIPT = "ACTION_LOAD_SCRIPT"
    # ACTION_CONNECTION_ESTABLISHED = "ACTION_CONNECTION_ESTABLISHED"
    # ACTION_CONNECTION_LISTEN = "ACTION_CONNECTION_LISTEN"
    # ACTION_CONNECTION_CREATE = "ACTION_CONNECTION_CREATE"


class Carbanakv2Operation(str, Enum):
    FILE_CLOSED = "FILE_CLOSED"
    FILE_CREATED = "FILE_CREATED"
    FILE_DELETED = "FILE_DELETED"
    FILE_OPENED = "FILE_OPENED"
    FILE_READ = "FILE_READ"
    FILE_RESTORED = "FILE_RESTORED"
    FILE_TRUNCATED = "FILE_TRUNCATED"
    FILE_WRITTEN = "FILE_WRITTEN"
    MODULE_LOADED = "MODULE_LOADED"
    NETFLOW_CONNECTED = "NETFLOW_CONNECTED"
    NETFLOW_CREATED = "NETFLOW_CREATED"
    NETFLOW_DISCONNECTED = "NETFLOW_DISCONNECTED"
    NETFLOW_PACKET_RECEIVED = "NETFLOW_PACKET_RECEIVED"
    NETFLOW_PACKET_SENT = "NETFLOW_PACKET_SENT"
    PROCESS_EXECUTED = "PROCESS_EXECUTED"
    REGISTRY_KEY_CREATED = "REGISTRY_KEY_CREATED"
    REGISTRY_KEY_DELETED = "REGISTRY_KEY_DELETED"
    REGISTRY_KEY_LOADED = "REGISTRY_KEY_LOADED"
    REGISTRY_KEY_OPENED = "REGISTRY_KEY_OPENED"
    REGISTRY_VALUE_DELETED = "REGISTRY_VALUE_DELETED"
    REGISTRY_VALUE_WRITTEN = "REGISTRY_VALUE_WRITTEN"

    # FILE_OPENED = "FILE_OPENED"
    # FILE_CLOSED = "FILE_CLOSED"
    # FILE_CREATED = "FILE_CREATED"
    # FILE_READ = "FILE_READ"
    # FILE_WRITTEN = "FILE_WRITTEN"
    # FILE_COPIED = "FILE_COPIED"
    # FILE_LINKED = "FILE_LINKED"
    # FILE_RENAMED = "FILE_RENAMED"
    # FILE_TRUNCATED = "FILE_TRUNCATED"
    # FILE_DELETED = "FILE_DELETED"
    # FILE_RESTORED = "FILE_RESTORED"
    # NETFLOW_CREATED = "NETFLOW_CREATED"
    # NETFLOW_CONNECTED = "NETFLOW_CONNECTED"
    # NETFLOW_PACKET_RECEIVED = "NETFLOW_PACKET_RECEIVED"
    # NETFLOW_PACKET_SENT = "NETFLOW_PACKET_SENT"
    # NETFLOW_DISCONNECTED = "NETFLOW_DISCONNECTED"
    # PROCESS_EXECUTED = "PROCESS_EXECUTED"
    # PROCESS_KILLED = "PROCESS_KILLED"
    # MODULE_LOADED = "MODULE_LOADED"
    # CROSS_PROCESS_INTERACTION = "CROSS_PROCESS_INTERACTION"
    # REGISTRY_KEY_LOADED = "REGISTRY_KEY_LOADED"
    # REGISTRY_KEY_UNLOADED = "REGISTRY_KEY_UNLOADED"
    # REGISTRY_KEY_OPENED = "REGISTRY_KEY_OPENED"
    # REGISTRY_KEY_CLOSED = "REGISTRY_KEY_CLOSED"
    # REGISTRY_KEY_CREATED = "REGISTRY_KEY_CREATED"
    # REGISTRY_KEY_RENAMED = "REGISTRY_KEY_RENAMED"
    # REGISTRY_KEY_REPLACED = "REGISTRY_KEY_REPLACED"
    # REGISTRY_KEY_DELETED = "REGISTRY_KEY_DELETED"
    # REGISTRY_KEY_RESTORED = "REGISTRY_KEY_RESTORED"
    # REGISTRY_VALUE_CREATED = "REGISTRY_VALUE_CREATED"
    # REGISTRY_VALUE_READ = "REGISTRY_VALUE_READ"
    # REGISTRY_VALUE_WRITTEN = "REGISTRY_VALUE_WRITTEN"
    # REGISTRY_VALUE_DELETED = "REGISTRY_VALUE_DELETED"


class SpadeGraspOperation(str, Enum):
    ACCEPT = "accept"
    CLONE = "clone"
    CLOSE = "close"
    CONNECT = "connect"
    CREATE = "create"
    EXECVE = "execve"
    EXIT = "exit"
    FORK = "fork"
    KILL = "kill"
    OPEN = "open"


class SysdigOperation(str, Enum):
    ACCEPT = "accept"
    CLONE = "clone"
    CLOSE = "close"
    CONNECT = "connect"
    CREATE = "create"
    EXECVE = "execve"
    EXIT = "exit"
    FORK = "fork"
    KILL = "kill"
    OPEN = "open"


class TcOperation(str, Enum):
    """Operations used for TC datasets."""

    EVENT_CONNECT = "EVENT_CONNECT"
    EVENT_EXECUTE = "EVENT_EXECUTE"
    EVENT_OPEN = "EVENT_OPEN"
    EVENT_READ = "EVENT_READ"
    EVENT_RECVFROM = "EVENT_RECVFROM"
    EVENT_RECVMSG = "EVENT_RECVMSG"
    EVENT_SENDMSG = "EVENT_SENDMSG"
    EVENT_SENDTO = "EVENT_SENDTO"
    EVENT_WRITE = "EVENT_WRITE"
    EVENT_CLONE = "EVENT_CLONE"


class TcOperationModified(str, Enum):
    """Operations used for TC datasets."""

    EVENT_CONNECT = "EVENT_CONNECT"
    EVENT_EXECUTE = "EVENT_EXECUTE"
    EVENT_OPEN = "EVENT_OPEN"
    EVENT_READ = "EVENT_READ"
    EVENT_RECVFROM = "EVENT_RECVFROM"
    EVENT_RECVMSG = "EVENT_RECVMSG"
    EVENT_SENDMSG = "EVENT_SENDMSG"
    EVENT_SENDTO = "EVENT_SENDTO"
    EVENT_WRITE = "EVENT_WRITE"
    EVENT_CLONE = "EVENT_CLONE"


class DatasetName(str, Enum):
    """Supported dataset identifiers from experiment config."""

    CADETS_E3 = "cadets_e3"
    CADETS_E3_LOTL = "cadets_e3_lotl"
    CADETS_E5 = "cadets_e5"
    CLEARSCOPE_E3 = "clearscope_e3"
    CLEARSCOPE_E5 = "clearscope_e5"
    THEIA_E3 = "theia_e3"
    THEIA_E3_LOTL = "theia_e3_lotl"
    THEIA_E5 = "theia_e5"
    OPTC_051 = "optc_051"
    OPTC_201 = "optc_201"
    OPTC_501 = "optc_501"
    ATLASV2_EDR = "atlasv2_edr"
    CARBANAKV2_EDR = "carbanakv2_edr"
    SPADE_GRASP = "spade_grasp"
    SYSDIG = "sysdig"


class PathTransformerConstants(str, Enum):
    """Constants for the transformer-based path representation."""

    CHARS = string.printable
    PADDING_CHAR = 0


class TimeStringFormat(str, Enum):
    """Standardized time string format."""

    FMT = "%Y-%m-%d %H:%M:%S"
